const recipe = [
  {
    name: "hugo",
    time: 75,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: "vegan",
    tag: ["veal", "pasta"],
  },
  {
    name: "martini",
    time: 15,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: "chicken",
    tag: ["veal", "pasta"],
  },
  {
    name: "margarita",
    time: 35,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "pasta"],
  },
  {
    name: "manhattan",
    time: 25,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["mixed meat", "pasta"],
  },
  {
    name: "earl Grey tea",
    time: 45,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["mixed meat", "pasta"],
  },
  {
    name: "herbal tea",
    time: 55,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: "fruit",
    tag: ["veal", "pasta"],
  },
  {
    name: "ginger ale",
    time: 65,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "vegatable"],
  },
  {
    name: "lemonade",
    time: 795,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "potato"],
  },
  {
    name: "traffic Light",
    time: 85,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "rice"],
  },
];
export default recipe;
