const recipe = [
  {
    name: "hugo",
    time: 75,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: "vegan",
    tag: ["veal", "pasta"],
    count: 0,
  },
  {
    name: "martini",
    time: 15,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: "chicken",
    tag: ["veal", "pasta"],
    count: 10,
  },
  {
    name: "margarita",
    time: 35,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "pasta"],
    count: 15,
  },
  {
    name: "manhattan",
    time: 25,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["mixed meat", "pasta"],
    favorite: true,
    count: 0,
  },
  {
    name: "earl Grey tea",
    time: 45,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["mixed meat", "pasta"],
    favorite: true,
    count: 0,
  },
  {
    name: "herbal tea",
    time: 55,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: "fruit",
    tag: ["veal", "pasta"],
    favorite: false,
    count: 2,
  },
  {
    name: "ginger ale",
    time: 65,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "vegatable"],
    favorite: false,
    count: 69,
  },
  {
    name: "lemonade",
    time: 795,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "potato"],
    favorite: true,
    count: 420,
  },
  {
    name: "traffic Light",
    time: 85,
    ingredients: ["lots", "of", "stuff", "but", "no", "idea", "tbh"],
    guide: ["order", "it", "online"],
    tag: ["veal", "rice"],
    favorite: true,
    count: 0,
  },
];
export default recipe;
